# Generated by Django 3.1 on 2020-08-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
            ],
        ),
        migrations.AddField(
            model_name='rooms',
            name='status',
            field=models.CharField(choices=[('a', 'available'), ('u', 'unavailable')], default='a', max_length=1),
        ),
    ]
