# Generated by Django 3.1 on 2020-08-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_rooms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='status',
            field=models.CharField(blank=True, choices=[('w', 'waiting'), ('d', 'done'), ('x', 'canceled')], default='w', help_text='Status', max_length=1),
        ),
    ]
