# Generated by Django 3.1 on 2020-08-07 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_reservations_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='name',
            new_name='title',
        ),
    ]
